# Generated by Django 2.2.12 on 2020-09-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-published',), 'verbose_name_plural': 'Galleries'},
        ),
    ]
