# Generated by Django 2.2.12 on 2020-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200908_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
