# Generated by Django 2.2.12 on 2020-09-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gallery_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='url',
        ),
    ]
